### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by CaspianA1** [jserv/ogc#3]
Does `gc_run()` need to be called from time-to-time for the garbage collector to be invoked, or will it do that on its own?

**Comment by jserv** [comment]
> Does `gc_run()` need to be called from time-to-time for the garbage collector to be invoked, or will it do that on its own?

You could invoke `gc_run` aggressively or lazily depending on the scenario where you are applying this garbage collector. However, current `ogc` fails to track all the objects across call stack.

**Comment by CaspianA1** [comment]
Thank you.
